Repository googleapis/google-resumable-media-python, pull requests merged in 2019-09, with the labels that each got.

#101 Release v0.4.0
  CHANGELOG.md
  docs/latest/.buildinfo
  docs/latest/_static/documentation_options.js
  docs/latest/genindex.html
  docs/latest/google.resumable_media.common.html
  docs/latest/google.resumable_media.requests.download.html
  docs/latest/google.resumable_media.requests.html
  docs/latest/google.resumable_media.requests.upload.html
  docs/latest/index.html
  docs/latest/objects.inv
  docs/latest/py-modindex.html
  docs/latest/search.html
  setup.py
Labels: autorelease: pending, cla: yes

#94 Add black.
  .flake8
  google/resumable_media/__init__.py
  google/resumable_media/_download.py
  google/resumable_media/_helpers.py
  google/resumable_media/_upload.py
  google/resumable_media/common.py
  google/resumable_media/requests/__init__.py
  google/resumable_media/requests/_helpers.py
  google/resumable_media/requests/download.py
  google/resumable_media/requests/upload.py
  noxfile.py
  synth.py
  tests/system/requests/conftest.py
  tests/system/requests/test_download.py
  tests/system/requests/test_upload.py
  tests/system/utils.py
  tests/unit/requests/test__helpers.py
  tests/unit/requests/test_download.py
  tests/unit/requests/test_upload.py
  tests/unit/test__download.py
  tests/unit/test__helpers.py
  tests/unit/test__upload.py
  tests/unit/test_common.py
Labels: cla: yes

#103 Revert "Always use raw response data. (#87)"
  docs/latest/.buildinfo
  google/resumable_media/_download.py
  google/resumable_media/requests/_helpers.py
  google/resumable_media/requests/download.py
  tests/system/requests/test_download.py
  tests/unit/requests/test__helpers.py
  tests/unit/requests/test_download.py
  tests/unit/test__download.py
Labels: cla: yes

#104 Release v0.4.1
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#108 Update URL for requests library's Sphinx inventory.
  docs/latest/.buildinfo
  docs/latest/_static/documentation_options.js
  docs/latest/genindex.html
  docs/latest/google.resumable_media.common.html
  docs/latest/google.resumable_media.requests.download.html
  docs/latest/google.resumable_media.requests.html
  docs/latest/google.resumable_media.requests.upload.html
  docs/latest/index.html
  docs/latest/objects.inv
  docs/latest/py-modindex.html
  docs/latest/search.html
  docs_build/conf.py
Labels: cla: yes, type: docs

#102 chore: remove CircleCI
  .circleci/config.yml
  README.rst
Labels: cla: yes

#105 Initial synth.
  synth.metadata
Labels: cla: yes, codegen
