Repository googleapis/google-resumable-media-python, pull requests merged in 2020-09, with the labels that each got.

#171 fix(lint): blacken 5 files
  google/resumable_media/_download.py
  google/resumable_media/_helpers.py
  tests/unit/requests/test_download.py
  tests/unit/requests/test_upload.py
  tests/unit/test__helpers.py
Labels: cla: yes

#170 fix: allow space between checksums in header
  google/resumable_media/_helpers.py
  tests/unit/test__helpers.py
Labels: cla: yes

#166 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#175 chore: add default CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#153 feat: async changes to resumable upload/download
  .kokoro/docker/docs/Dockerfile
  CHANGELOG.md
  google/async_resumable_media/_download.py
  google/async_resumable_media/_helpers.py
  google/async_resumable_media/_upload.py
  google/async_resumable_media/common.py
  google/async_resumable_media/requests/__init__.py
  google/async_resumable_media/requests/_request_helpers.py
  google/async_resumable_media/requests/download.py
  google/async_resumable_media/requests/upload.py
  google/resumable_media/_download.py
  google/resumable_media/_helpers.py
  google/resumable_media/requests/upload.py
  noxfile.py
  setup.py
  synth.metadata
  tests/unit/requests/test_download.py
  tests/unit/requests/test_upload.py
  tests/unit/test__helpers.py
  tests_async/system/requests/conftest.py
  tests_async/system/requests/test_download.py
  tests_async/system/requests/test_upload.py
  tests_async/unit/requests/test__helpers.py
  tests_async/unit/requests/test_download.py
  tests_async/unit/requests/test_upload.py
  tests_async/unit/test__download.py
  tests_async/unit/test__helpers.py
  tests_async/unit/test__upload.py
  tests_async/unit/test_common.py
Labels: cla: no

#176 chore(deps): use google-auth >= 1.22.0, 2.0dev which includes google.auth.default_async, aiohttp_requests
  google/async_resumable_media/requests/_request_helpers.py
  noxfile.py
  setup.py
  tests_async/system/requests/conftest.py
  tests_async/system/requests/test_download.py
  tests_async/unit/test__download.py
Labels: cla: yes

#178 fix: move `async_resumable_media` to `_async_resumable_media`
  README.rst
  google/_async_resumable_media/__init__.py
  google/_async_resumable_media/_download.py
  google/_async_resumable_media/_helpers.py
  google/_async_resumable_media/_upload.py
  google/_async_resumable_media/requests/__init__.py
  google/_async_resumable_media/requests/_request_helpers.py
  google/_async_resumable_media/requests/download.py
  google/_async_resumable_media/requests/upload.py
  noxfile.py
  tests_async/system/requests/test_download.py
  tests_async/system/requests/test_upload.py
  tests_async/unit/requests/test__helpers.py
  tests_async/unit/requests/test_download.py
  tests_async/unit/requests/test_upload.py
  tests_async/unit/test__download.py
  tests_async/unit/test__helpers.py
  tests_async/unit/test__upload.py
Labels: cla: yes
