Repository googleapis/google-resumable-media-python, pull requests merged in 2020-08, with the labels that each got.

#155 docs: update docs build (via synth)
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  noxfile.py
  synth.metadata
  synth.py
Labels: cla: yes

#158 testing: harden systest teardowns vs transient GCS errors
  noxfile.py
  tests/system/requests/conftest.py
  tests/system/requests/test_upload.py
  tests/system/utils.py
Labels: cla: yes, testing

#160 chore(deps): pin 'google-crc32c < 0.2dev'
  setup.py
Labels: cla: yes

#159 chore: reset docker base (via synth)
  .kokoro/docker/docs/Dockerfile
  synth.metadata
Labels: cla: yes, context: none

#162 feat: bump 'google-crc32c >= 1.0'
  google/resumable_media/_helpers.py
  setup.py
Labels: cla: yes

#142 chore(packaging): update dev status to stable
  setup.py
Labels: cla: yes, type: process
