Repository googleapis/google-resumable-media-python, pull requests merged in 2021-05, with the labels that each got.

#218 tests: pin systest dep pytest-asyncio
  noxfile.py
Labels: api: storage, cla: yes

#217 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: storage, automerge, cla: yes

#208 build: use PyPI API token in secret manager
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: storage, cla: yes, context: full

#216 feat: allow RetryStrategy to be configured with a custom initial wait and multiplier
  google/resumable_media/_helpers.py
  google/resumable_media/common.py
  tests/unit/test__helpers.py
  tests/unit/test_common.py
Labels: api: storage, cla: yes
